package com.group10.koiauction.entity.enums;

public enum KoiStatusEnum {
    AVAILABLE,PENDING,PENDING_AUCTION , SELLING , DELIVER_REQUIRED , DELIVERING_TO_BUYER,RETURNING,SOLD,UNAVAILABLE,IS_DELETED

}
